// <auto-generated />
namespace FootballWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class post_tags2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_tags2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012192349113_post_tags2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
